"""Report Generator — synthesizes specialist findings into structured reports.

Template-based report generation for the PoC (no LLM call needed).
Supports three report modes: quick_answer, route_recommendation, risk_assessment.
"""

import logging
from typing import Optional

from google.adk.tools import ToolContext
from google.genai import types as adk_types

from solace_agent_mesh.agent.tools.dynamic_tool import DynamicTool

log = logging.getLogger(__name__)

REPORT_MODES = ("quick_answer", "route_recommendation", "risk_assessment")


def _format_quick_answer(question: str, evidence: dict) -> str:
    """Format a quick answer report."""
    lines = [
        f"## Quick Answer",
        f"**Question:** {question}",
        "",
    ]

    for specialist, data in evidence.items():
        lines.append(f"### {specialist}")
        if isinstance(data, dict):
            for k, v in data.items():
                lines.append(f"- **{k}:** {v}")
        elif isinstance(data, str):
            lines.append(data)
        lines.append("")

    return "\n".join(lines)


def _format_route_recommendation(question: str, evidence: dict) -> str:
    """Format a route recommendation report."""
    lines = [
        "## Route Recommendation Report",
        f"**Query:** {question}",
        "",
    ]

    # Route info
    route_data = evidence.get("route_calculator", evidence.get("RouteOptimizer", {}))
    if route_data:
        lines.append("### Route Details")
        if isinstance(route_data, dict):
            dist = route_data.get("total_distance_nm", "N/A")
            fuel = route_data.get("estimated_fuel_impact_pct", "N/A")
            wps = len(route_data.get("waypoints", []))
            lines.extend([
                f"- **Total Distance:** {dist} nm",
                f"- **Fuel Impact:** {fuel}%",
                f"- **Waypoints:** {wps}",
                "",
            ])

    # Risk info
    risk_data = evidence.get("risk_scorer", evidence.get("RiskAssessor", {}))
    if risk_data:
        lines.append("### Risk Assessment")
        if isinstance(risk_data, dict):
            score = risk_data.get("collision_risk_score", "N/A")
            level = risk_data.get("risk_level", "N/A")
            rec = risk_data.get("recommendation", "")
            lines.extend([
                f"- **Risk Score:** {score}",
                f"- **Risk Level:** {level}",
                f"- **Recommendation:** {rec}",
                "",
            ])

    # Weather info
    weather_data = evidence.get("weather", evidence.get("WeatherAnalyst", {}))
    if weather_data:
        lines.append("### Weather Conditions")
        if isinstance(weather_data, dict):
            for k, v in weather_data.items():
                lines.append(f"- **{k}:** {v}")
        lines.append("")

    # Migration info
    migration_data = evidence.get("migration_model", evidence.get("WhaleMigrationTracker", {}))
    if migration_data:
        lines.append("### Whale Migration")
        if isinstance(migration_data, dict):
            density = migration_data.get("density", "N/A")
            phase = migration_data.get("migration_phase", "N/A")
            species = migration_data.get("species_present", [])
            lines.extend([
                f"- **Peak Density:** {density}",
                f"- **Migration Phase:** {phase}",
                f"- **Species Present:** {', '.join(str(s) for s in species) if species else 'N/A'}",
                "",
            ])

    # Additional specialist data
    handled_keys = {"route_calculator", "RouteOptimizer", "risk_scorer", "RiskAssessor",
                    "weather", "WeatherAnalyst", "migration_model", "WhaleMigrationTracker"}
    for specialist, data in evidence.items():
        if specialist not in handled_keys:
            lines.append(f"### {specialist}")
            if isinstance(data, dict):
                for k, v in data.items():
                    lines.append(f"- **{k}:** {v}")
            elif isinstance(data, str):
                lines.append(data)
            lines.append("")

    lines.append("---")
    lines.append("*Report generated by Whale Agent Route Recommendation Engine*")

    return "\n".join(lines)


def _format_risk_assessment(question: str, evidence: dict) -> str:
    """Format a risk assessment report."""
    lines = [
        "## Risk Assessment Report",
        f"**Query:** {question}",
        "",
    ]

    # Risk scoring
    risk_data = evidence.get("risk_scorer", evidence.get("RiskAssessor", {}))
    if risk_data and isinstance(risk_data, dict):
        lines.append("### Collision Risk Score")
        lines.extend([
            f"- **Overall Score:** {risk_data.get('collision_risk_score', 'N/A')}",
            f"- **Risk Level:** {risk_data.get('risk_level', 'N/A')}",
            f"- **Recommendation:** {risk_data.get('recommendation', 'N/A')}",
            "",
        ])
        components = risk_data.get("components", {})
        if components:
            lines.append("### Risk Components")
            for k, v in components.items():
                lines.append(f"- **{k}:** {v}")
            lines.append("")

    # Incidents
    incident_data = evidence.get("incident_analyzer", evidence.get("IncidentAnalyst", {}))
    if incident_data and isinstance(incident_data, dict):
        lines.append("### Historical Incidents")
        total = incident_data.get("total_incidents", 0)
        lethal = incident_data.get("lethal_incidents", 0)
        lines.extend([
            f"- **Total Incidents:** {total}",
            f"- **Lethal Incidents:** {lethal}",
        ])
        breakdown = incident_data.get("species_breakdown", {})
        if breakdown:
            lines.append("- **Species Breakdown:**")
            for sp, count in breakdown.items():
                lines.append(f"  - {sp}: {count}")
        lines.append("")

    # Other evidence
    handled_keys = {"risk_scorer", "RiskAssessor", "incident_analyzer", "IncidentAnalyst"}
    for specialist, data in evidence.items():
        if specialist not in handled_keys:
            lines.append(f"### {specialist}")
            if isinstance(data, dict):
                for k, v in data.items():
                    lines.append(f"- **{k}:** {v}")
            elif isinstance(data, str):
                lines.append(data)
            lines.append("")

    lines.append("---")
    lines.append("*Report generated by Whale Agent Risk Assessment Engine*")

    return "\n".join(lines)


_FORMATTERS = {
    "quick_answer": _format_quick_answer,
    "route_recommendation": _format_route_recommendation,
    "risk_assessment": _format_risk_assessment,
}


def generate_report(
    question: str,
    evidence: dict,
    report_mode: str = "quick_answer",
) -> dict:
    """Generate a formatted report from specialist evidence."""
    if report_mode not in REPORT_MODES:
        return {"error": f"Unknown report_mode '{report_mode}'. Must be one of: {REPORT_MODES}"}

    formatter = _FORMATTERS[report_mode]
    formatted = formatter(question, evidence)

    return {
        "formatted_report": formatted,
        "report_mode": report_mode,
        "specialists_used": list(evidence.keys()),
        "question": question,
    }


class ReportGeneratorTool(DynamicTool):
    """Synthesizes specialist findings into a structured report."""

    @property
    def tool_name(self) -> str:
        return "report_generator"

    @property
    def tool_description(self) -> str:
        return (
            "Synthesizes specialist findings into a structured route recommendation "
            "or risk assessment report. Template-based generator supporting "
            "quick_answer, route_recommendation, and risk_assessment modes."
        )

    @property
    def parameters_schema(self) -> adk_types.Schema:
        return adk_types.Schema(
            type=adk_types.Type.OBJECT,
            properties={
                "question": adk_types.Schema(
                    type=adk_types.Type.STRING,
                    description="The original user question",
                ),
                "evidence": adk_types.Schema(
                    type=adk_types.Type.OBJECT,
                    description="Dict of specialist responses keyed by specialist name",
                ),
                "report_mode": adk_types.Schema(
                    type=adk_types.Type.STRING,
                    description="Report mode: quick_answer, route_recommendation, risk_assessment",
                    nullable=True,
                ),
            },
            required=["question", "evidence"],
        )

    async def _run_async_impl(
        self,
        args: dict,
        tool_context: Optional[ToolContext] = None,
        credential: Optional[str] = None,
    ) -> dict:
        question = args.get("question", "")
        evidence = args.get("evidence", {})
        report_mode = args.get("report_mode", "quick_answer")

        if not question:
            return {"error": "question is required"}
        if not isinstance(evidence, dict):
            return {"error": "evidence must be a dict"}

        return generate_report(question, evidence, report_mode)
